import "./globals.css";
import Navigation from "./components/Navigation";
import Footer from "./components/Footer";
import CookieConsent from "./components/CookieConsent";
import { SessionProvider } from "./components/SessionProvider";

export const metadata = {
    title: "VICMART ENTERPRISES",
    description: "Generated by create next app",
};

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning={true}>
            <head></head>
            <body suppressHydrationWarning={true}>
                <SessionProvider>
                    <Navigation />
                    {children}
                    <Footer />
                    <CookieConsent />
                </SessionProvider>
            </body>
        </html>
    );
}
