import { NextResponse } from "next/server";

export async function GET() {
    const products = [
        {
            src: "/assets/images/non-foods/enchanteur-1.jpg",
            alt: "Enchanteur",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/nivea.jpg",
            alt: "Nivea",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInDown",
        },
        {
            src: "/assets/images/non-foods/dark-and-lovely-1.jpg",
            alt: "Dark and Lovely",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/Duracell logo.jpg",
            alt: "Duracell",
            width: 170,
            height: 95,
            id: "nonfd",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/tiger-razor.jpg",
            alt: "Tiger Razor",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInDown",
        },
        {
            src: "/assets/images/non-foods/henkel.png",
            alt: "Henkel",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/niviamen1.jpg",
            alt: "Nivea Men",
            width: 170,
            height: 95,
            id: "nivea",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/oral.jpg",
            alt: "Oral",
            width: 170,
            height: 95,
            id: "oral",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/gillette.png",
            alt: "Gillette",
            width: 170,
            height: 85,
            id: "",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/ariel-1.jpg",
            alt: "Ariel",
            width: 170,
            height: 85,
            id: "ariel",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/always.png",
            alt: "Always",
            width: 170,
            height: 90,
            id: "always",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/safequard.png",
            alt: "Safeguard",
            width: 170,
            height: 90,
            id: "safe",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/Godrej.webp",
            alt: "Godrej",
            width: 170,
            height: 85,
            id: "",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/dabur.png",
            alt: "Dabur",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInDown",
        },
        {
            src: "/assets/images/non-foods/loreal.webp",
            alt: "Loreal",
            width: 170,
            height: 95,
            id: "nonfd",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/unilever.webp",
            alt: "Unilever",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInUp",
        },
        {
            src: "/assets/images/non-foods/vini.png",
            alt: "Vini",
            width: 170,
            height: 95,
            id: "",
            className: "fadeInUp",
        },
    ];

    return NextResponse.json(products);
}
